# Generated by Django 5.0.6 on 2024-06-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_employee_email_employee_name_employee_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
