# Generated by Django 5.0.6 on 2024-06-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_remove_employee_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
