# Generated by Django 5.0.6 on 2024-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='ems.employee'),
        ),
    ]
